### ISSUE TITLE
realm::experimental::db as std::unique_ptr?

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#115]
I'm setting up my syncRealm (`realm::experimental::db`) as a unique_ptr. 

I'm getting a crash when calling `add`. Is there something in the design that means it should be used in a `unique_ptr`? Or am I doing something else wrong?

**Comment by leemaguire** [comment]
@adamski can you share the code that reproduces the issue?

**Comment by adamski** [comment]
Sorry it was a silly order of initialisation issue!
