### ISSUE TITLE
Why the requirement for macOS 12 or later? 

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#130]
I'm concerned that requiring macOS 12 will exclude a sizeable chunk of my customers. 

Some data from another vendor in our industry (audio plugins):

```
macOS 10.x = 31%
macOS 11   = 8%
macOS 12   = 23%
macOS 13   = 25%
macOS 14   = 10%
```

Assuming this data also represents my customers, I'd potentially be excluding 39% of them by forcing this requirement. A lot of music producers will stay on older macOS versions for various reasons. 

Can you please explain why this requirement is necessary, and if there is a way to reduce it, ideally back to Catalina or Mojave?

Thank you

**Comment by adamski** [comment]
Actually I just tried building for 10.15 Catalina and it builds fine.

It seems that the only issue in supporting earlier versions is the use of C++17 `std::filesystem::path` which requires 10.15 or later.

May I propose to use this header-only library to replace which will enable lower versions to be supported (apparently down to 10.12): https://github.com/gulrak/filesystem

**Comment by leemaguire** [comment]
@adamski we currently only test as low as macOS 12 and that is the reason for it being the minimum supported version. We can setup more CI actions to test against older macOS versions which should help you here.

**Comment by leemaguire** [comment]
@adamski I'll see if there's a way to do this without the need for a 3rd party lib.

**Comment by adamski** [comment]
@leemaguire any update on this issue?

**Comment by kneth** [comment]
@adamski I'll discuss it with Lee when he is back next week.

**Comment by leemaguire** [comment]
@adamski I'll add the ability for our CI to test the lowest possible deployment target. Currently the lowest macOS version that I can build and test locally successfully is 10.15.

**Comment by adamski** [comment]
> @adamski I'll add the ability for our CI to test the lowest possible deployment target. Currently the lowest macOS version that I can build and test locally successfully is 10.15.

10.15 is totally fine, thanks !
