### ISSUE TITLE
creating pointer to "realm instance" inside a class context - The idea is to persist & reuse the instance for multiple READ/WRITE operations 

### ISSUE THREAD

**Issue by vtharmalingam** [realm/realm-cpp#144]
Hi,

For my app, I would like to create a class that can serve as an interface between my application code and realm DB. 
So I am writing a class called "MyRealmInf" with a constructor that creates and initialize the pointer to "realm_instance" like this:

```
// Header:

class MyRealmInf
{
	private:
	realm::experimental::db* realm_instance = nullptr;

	public:
		MyRealmInf();
};

```

```cpp
# .CPP file. The below is inside the constructor

 // .... create config

 auto realm = realm::experimental::db(std::move(config));
 realm_instance = &realm

...

```

My code compiles, but throws runtime exception when I use the "realm_instance" to write record(s). I am unable to figure out what is causing the error.

It would be great if someone could educate me what I am missing in the above design... Or perhaps, can guide me with a better design given my requirement stated above. Thanks, in advance.

**Comment by vtharmalingam** [comment]
I have an observation: When I replace the simple pointer with smart_ptr it works.. I am not sure why not with simple pointer. Any thoughts?

**Comment by leemaguire** [comment]
```cpp
auto realm = realm::experimental::db(std::move(config));
 realm_instance = &realm
```
@vtharmalingam in the above code the `realm` instance will be created on the stack, so when you exit the scope the reference will be null. You need to create the instance on the heap. A smart pointer would be the best choice for this so that you don't need to manually manage the lifecycle of the pointer, otherwise you need to do:

```cpp
 realm_instance = new realm::experimental::db(std::move(config));
```

**Comment by vtharmalingam** [comment]
Got you, thanks @leemaguire :)
