### ISSUE TITLE
 error: no template named 'managed';

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#148]
When building from the main branch.

Probably related to the removal of the `experimental` namespace: 

Without

```cpp
using namespace realm;
```

I get 
```
 error: no template named 'managed'; did you mean 'realm::managed'?
REALM_EMBEDDED_SCHEMA (TonalDBKey, degree, period, name)
^
```

**Comment by leemaguire** [comment]
@adamski this is expected, when declaring your Realm models they need to be declared inside of `namespace realm`.

**Comment by adamski** [comment]
I prefer not to have to use `using namespace realm`. 

The alternative is to wrap each macro call with `namespace realm`. This quickly gets cluttered though. 

@leemaguire Would it be possible to add the namespace directly to the macros e.g.

```cpp
#define REALM_EMBEDDED_SCHEMA(cls, ...) \
    namespace realm { \
    DECLARE_REALM_SCHEMA(cls, true, false, experimental::BetaObjectType::Embedded, __VA_ARGS__) \
```

At least that works in my testing and allows my code to look cleaner.

**Comment by adamski** [comment]
Actually maybe not... I can live with `using namespace realm` :)

**Comment by adamski** [comment]
Closing, not an issue
