### ISSUE TITLE
token index not respecting current results set

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#152]
I'm using a notification token to get updates about changes. 

I have a couple of different views into the same collection ("public" and "user"). 

I expected that the index returned by the deletions/insertions/modifications vectors in `changes` would report based on the results set. What I'm seeing is based on the entire collection. 

For example if I modify the last created item, I get the index of the last item of the entire collection, not of the current results set. 

If this is tricky  - would it be possible to get the ID of deleted or modified items?

**Comment by adamski** [comment]
@leemaguire any insight into the above?

**Comment by leemaguire** [comment]
Hi @adamski 

Could you share some example code so I can better understand the issue?
