### ISSUE TITLE
CMake options

### ISSUE THREAD

**Issue by dikazjanos** [realm/realm-cpp#157]
Hello! I tried building the library with CMake options, taken from realm-core, and this project, but they don't seem to apply. Even when doing `set(REALM_NO_TESTS ON CACHE BOOL "")`, the tests are being built, which subsequently fails because I set REALM_ENABLE_SYNC to off. REALM_FETCH_MISSING_DEPENDENCIES also doesn't take effect.

Are there any plans to improve the customisation situation?

**Comment by kneth** [comment]
The SDK is a sync-only SDK, and setting `REALM_ENABLE_SYNC` to off is not supported.
