### ISSUE TITLE
Optional string in a model throws partial specializations ambiguity error

### ISSUE THREAD

**Issue by ahmdmhd** [realm/realm-cpp#17]
Defining an optional string in a model throws a `Ambiguous partial specializations of 'persisted_type<std::optional<std::string>>'` compilation error in Xcode. I'm defining a model as such:

```cpp
struct Model: realm::object {
  realm::persisted<std::optional<std::string>> optional_string;

  using schema = realm::schema<"model",
  realm::property<"optional_string", &Model::optional_string>
  >;
};
```

How is it possible to define an optional string? Thank you :)

**Comment by jsflax** [comment]
Hey @ahmdmhd,

This is a bug that will be fixed later today. I will link the PR shortly. Thanks for the catch!

**Comment by jsflax** [comment]
@ahmdmhd This will be fixed by: https://github.com/realm/realm-cpp/pull/18

Note that we are now supporting cpp17, so the schema does have to be declared slightly differently:
```cpp
struct Model: realm::object {
  realm::persisted<std::optional<std::string>> optional_string;

  static constexpr auto schema = realm::schema("model",
      realm::property<&Model::optional_string>("optional_string")
  );
};
```

Once the PR is passing on CI, I will merge it.

**Comment by jsflax** [comment]
@ahmdmhd this should work now. Please check it out and let us know.

**Comment by ahmdmhd** [comment]
Hi @jsflax, thank you for the updates! I tried the recent changes and it's working properly now!

I will close the issue :)
