### ISSUE TITLE
Windows build error with 1.1.0

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#191]
### What happened?

Using realm-cpp version 1.1.0 via CMake, I get a compilation error because the contents of `sdk.hpp` is only a path:
```
../../src/cpprealm/sdk.hpp
```

### Repro steps

Add realm via CPM:

```
CPMAddPackage(NAME cpprealm
        GIT_REPOSITORY https://github.com/realm/realm-cpp.git
        GIT_TAG v1.1.0
)
```

Then 

```
target_link_libraries(${PROJECT_NAME} cpprealm ...)
```

Then I get:

```
<path-to>\Cache\cpprealm\61e53a81097c805b409b6f123e8c638ce1f4ee29\include\cpprealm\sdk.hpp(1,1): error C2059: syntax error: '.' 
  ```

### Version

1.1.0

### Installation method

CPM

### What Atlas Services are you using?

Atlas Device Sync

### Compiler

Visual Studio 17

### OS and version

Windows 10

### Code snippets

```
#include <cpprealm/sdk.hpp>
```

### Relevant log output

```
<path-to>\Cache\cpprealm\61e53a81097c805b409b6f123e8c638ce1f4ee29\include\cpprealm\sdk.hpp(1,1): error C2059: syntax error: '.' 
  ```

**Comment by leemaguire** [comment]
Hey @adamski, This is caused by Windows not supporting symbolic links out of the box. You'll need to enable symbolic links first and then try rebuilding. Ultimately we plan to move the actual headers into the include folder so that you don't face this issue in the future.

**Comment by adamski** [comment]
@leemaguire can you please point me to a guide for how to do that? 

It looks like there's a PR on the way so I might just wait for that.. 

Thanks
