### ISSUE TITLE
Proxy-Settings not working since version 1.1.1

### ISSUE THREAD

**Issue by GR-C** [realm/realm-cpp#226]
### What happened?

Hello,

After updating from version `1.0.0` to version `2.1.0`, I noticed that the proxy settings no longer take effect. I checked the code and identified the cause in the modification of the `send_request_to_server` method (https://github.com/realm/realm-cpp/commit/f643313fabeeae25f58907200140590205f03ca1) due to `Issue 189`.

At first glance, it appears that the proxy address requires a scheme. That works, but it’s only by coincidence. The call `proxy_uri.get_auth(proxy_userinfo, proxy_host, proxy_port);` provides the hostname (for `proxy_host`) inadvertently by specifying the scheme. However, if you look into the `proxy_uri` variable, you will see that the hostname is stored in the `m_auth` property and not under `m_path`, where I believe it belongs.

Regards
Giuseppe

### Repro steps

I specify the proxy settings like in the code below.

```
auto appConfig = realm::App::configuration();
appConfig.app_id = "myAppId";

// other configuration steps here...

realm::proxy_config proxyConfig;
proxyConfig.address  = address = "proxy.example.com";
proxyConfig.port = 8888; 

appConfig.proxy_configuration = proxyConfig;

auto app = realm::App(appConfig);
auto user = app.login(apiKey).get(); // Login throws an app_error exception saying "Invalid argument" 
```

### Version

2.1.0

### Installation method

Manual compile

### What Atlas Services are you using?

Atlas Device Sync

### Compiler

MSBuild

### OS and version

Windows 11

**Comment by leemaguire** [comment]
Hi @GR-C, This will be addressed in https://github.com/realm/realm-cpp/pull/216

**Comment by nirinchev** [comment]
Closing since #216 was merged.
