### ISSUE TITLE
musl aarch64 build fails

### ISSUE THREAD

**Issue by BestITUserEUW** [realm/realm-cpp#26]
Hey,
i'm trying to build realm-cpp with musl instead of libc, build fails.

Musl Version: 1.2.3
Openssl: 3.0.7
Zlib: 1.2.13
Curl: 7.86.0
Toolchain: https://github.com/dockcross/dockcross Image: linux-arm64-musl

Build Error:
> [ 21%] Building CXX object realm-core/src/realm/CMakeFiles/Storage.dir/query.cpp.o
In file included from /usr/aarch64-linux-musl-cross/aarch64-linux-musl/include/c++/9.4.0/cstdint:41,
                 from /work/build/thirdParty/realm-cpp/external-realm-cpp/src/external-realm-cpp/realm-core/src/realm/query.hpp:22,
                 from /work/build/thirdParty/realm-cpp/external-realm-cpp/src/external-realm-cpp/realm-core/src/realm/query.cpp:19:
/usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[5]: *** [realm-core/src/realm/CMakeFiles/Storage.dir/build.make:76: realm-core/src/realm/CMakeFiles/Storage.dir/query.cpp.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:379: realm-core/src/realm/CMakeFiles/Storage.dir/all] Error 2
gmake[4]: *** Waiting for unfinished jobs....
[ 21%] Building CXX object _deps/catch2-build/src/CMakeFiles/

**Comment by leemaguire** [comment]
Hi @BestITUserEUW we do not support this toolchain.
