### ISSUE TITLE
Will this SDK be compatible with Windows?

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#3]
And in general for desktop applications?

Ideally where there can be multiple instances of an application running in memory all accessing the same DB.

**Comment by jsflax** [comment]
I believe @GabrielEnriquezXR was able to get this compiling for windows recently, so there would be no reason to not be able to use it for desktop applications.

For multiple instances of an application running in memory all accessing the same DB, we support this functionality as long as the realm is not encrypted or using sync.

**Comment by GabrielEnriquezXR** [comment]
I was not able to make it work unfortunately. The farthest I got was fixing the initial dependencies in CMake and producing a .sln file. After that, I encountered a couple of errors that I'm not quite sure how to fix. I'm still waiting for official documentation on how to use this SDK, or perhaps a sample project.

**Comment by kneth** [comment]
Windows is supported now.
