### ISSUE TITLE
Android Example app build fails

### ISSUE THREAD

**Issue by azeeka** [realm/realm-cpp#62]
The example android project in the repo fails to build. Apparently realm-core was updated, because it can not find `realm/util/http.hpp`: 

```
/Users/user/repo/github/realm-cpp/src/cpprealm/internal/android/network_transport.cpp:20:10: fatal error: 'realm/util/http.hpp' file not found
```

Quick search in the root directory shows that it is located in `./realm-core/src/realm/sync/network/http.hpp`. If I try to fix the include line, it gives a lot of new build errors related to `realm::util`

Could you please look into it? And if the example android app builds successfully?

**Comment by leemaguire** [comment]
Hi @azeeka could you use the branch `lm/cached-realm` for the time being? It should solve your issue.

**Comment by azeeka** [comment]
> Hi @azeeka could you use the branch `lm/cached-realm` for the time being? It should solve your issue.

Ah, thank you so much! Works flawlessly!
