### ISSUE TITLE
Issue with REALM_SCHEMA usage

### ISSUE THREAD

**Issue by pduvalla** [realm/realm-cpp#89]
I am observing an issue with REALM_SCHEMA usage in Coffee project , details below

SDK: V0.2.0  preview for SDK c++
Ubuntu 20.04
Qt Creator 4.11.1

ISSUE: realm_models.hpp:17:5: error: reference to local variable 'ptr' declared in enclosing lambda expression
macros.hpp:273:5: note: expanded from macro 'REALM_SCHEMA'
macros.hpp:303:26: note: expanded from macro 'DECLARE_REALM_SCHEMA'
realm_models.hpp:17:5: note: 'ptr' declared here
macros.hpp:273:5: note: expanded from macro 'REALM_SCHEMA'
macros.hpp:301:39: note: expanded from macro 'DECLARE_REALM_SCHEMA'

**Comment by leemaguire** [comment]
Hi @pduvalla which gcc version are you using?

**Comment by pduvalla** [comment]
gcc 9.4.0

**Comment by leemaguire** [comment]
We only support a minimum of GCC 11.

**Comment by pduvalla** [comment]
Seeing the following error with gcc 11
In file included from /usr/include/c++/11/bits/stl_algo.h:59,
                 from /usr/include/c++/11/algorithm:62,
                 from ../../../../Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h:142,
                 from ../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h:43,
                 from ../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui/qguiapplication.h:43,
                 from ../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui/QGuiApplication:1,
                 from ../coffee/main.cpp:4:
/usr/include/c++/11/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~

**Comment by leemaguire** [comment]
These errors aren't related to Realm, you might need some configuration in your Qt project, maybe [this SO](https://stackoverflow.com/questions/52532936/usr-include-c-7-cstdlib7515-fatal-error-stdlib-h-no-such-file-or-directo) post might have some answers for you.

**Comment by pduvalla** [comment]
Thanks!  fatal error: stdlib.h: No such file or directory is resolved but still seeing ...
realm_models.hpp:17:5: error: reference to local variable 'ptr' declared in enclosing lambda expression
macros.hpp:273:5: note: expanded from macro 'REALM_SCHEMA'
macros.hpp:303:26: note: expanded from macro 'DECLARE_REALM_SCHEMA'
realm_models.hpp:17:5: note: 'ptr' declared here
macros.hpp:273:5: note: expanded from macro 'REALM_SCHEMA'
macros.hpp:301:39: note: expanded from macro 'DECLARE_REALM_SCHEMA'

Can you share the build environment used to verify this example , like the QT version, and gcc version etc

**Comment by leemaguire** [comment]
I verified the example on macOS 13, Qt 6.4.1, and clang 14.0.3

**Comment by pduvalla** [comment]
@leemaguire ,  Is there a work around to make it work with 
Ubuntu 20.04
Qt Creator 4.11.1
gcc 11 and g++ 11 

I see the same error in hello world example too.

Thanks

**Comment by leemaguire** [comment]
I will have to test it out on Ubuntu 20.04 and get back to you, the minimum Ubuntu version we test on currently is 22.04
